frontend:
  image: realsahilthakur/sahilthakur:frontend
  nodePort: 30080

backend:
  image: realsahilthakur/sahilthakur:backend

postgres:
  image: postgres:15
  user: user
  password: pass
  db: mydb
